In [10]:
#1 MATRIX ADDITION

In [ ]:
#1a without numpy

In [39]:
def matrixAdd(a, b):
    for i in range(0, len(a)):
        for j in range(0, len(a[0])):
            c = [[a[i][j] + b[i][j] for j in range(len(a[0]))] for i in range(len(a))]
    for r in c:
        print(r)
    

In [40]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[0,1,2],[2,3,4],[4,5,6]]
matrixAdd(a,b)

[1, 3, 5]
[6, 8, 10]
[11, 13, 15]


In [41]:
c = [[2,3,4,5],[1,2,3,4]]
d = [[1,2,3,4], [5,6,7,8]]
matrixAdd(c,d)

[3, 5, 7, 9]
[6, 8, 10, 12]


In [ ]:
#2 with numpy

In [42]:
import numpy as np

In [43]:
a = np.array([[2,3,4,5],[1,2,3,4]])
b = np.array([[1,2,3,4],[5,6,7,8]])
c = np.add(a,b)
c

array([[ 3,  5,  7,  9],
       [ 6,  8, 10, 12]])

In [44]:
#2 matrix multiplication

In [45]:
#2a without numpy

In [74]:
def matrixMul(a,b):
    sum = 0
    c = []
    
    #initialising the array to 0
    for i in range(len(a)):
        col = []
        for j in range(len(b[0])):
            col.append(0)
        c.append(col)
    
    #performing multiplication
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(a[0])):
                sum = sum+a[i][k]*b[k][j]
            c[i][j] = sum
            sum = 0
    print(c)

In [75]:
a = [[2,3,1],[3,2,1],[4,3,1]]
b = [[1,0,0],[0,1,0],[0,0,1]]
matrixMul(a,b)

[[2, 3, 1], [3, 2, 1], [4, 3, 1]]


In [ ]:
#2b using numpy

In [80]:
# following code multiplies corresponding elements of two matrices
c = np.array([[2,3,1],[3,2,1],[4,3,1]])
d = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(c*d)
print(np.multiply(a,b))


[[2 0 0]
 [0 2 0]
 [0 0 1]]
[[2 0 0]
 [0 2 0]
 [0 0 1]]


In [81]:
print(np.dot(a,b))

[[2 3 1]
 [3 2 1]
 [4 3 1]]


In [ ]:
#3 inverse of a matrix

In [ ]:
#3a without numpy

In [82]:
#defining the function to get the minor matrix after excluding i-th row and j-th column
def getcofactor(a, i, j):
    return [row[:j] + row[j+1:] for row in (a[:i] + a[i+1:])]

In [83]:
def determinant(a):
    #if order is 2 then simple cross multiplication:
    if len(a) == 2:
        return a[0][0]*a[1][1] - a[0][1]*a[1][0]
    
    sum = 0
    
    #loop to traverse each column of matrix a.
    
    for curr_col in range(len(a)):
        
        sign = (-1)**(curr_col)
        
        sub_det = determinant(getcofactor(a,0,curr_col))
        
        sum+= (sign*a[0][curr_col]*sub_det)
        
    return sum

In [86]:
a = [[2,0,0,0],[0,2,0,0],[0,0,2,0],[0,0,0,2]]
print(determinant(a))

16


In [95]:
def cofactor(a):
    b = []
    
    for i in range(len(a)):
        col=[]
        for j in range(len(a[0])):
            col.append(0)
        b.append(col)
        
    for i in range(len(a)):
        for j in range(len(a[0])):
            sign = (-1)**(i+j)
            b[i][j] = sign*determinant(getcofactor(a,i,j))
            
    return b

In [96]:
a = [[1,1,2],[-1,0,1],[2,1,0]]
b = cofactor(a)
print(b)

[[-1, 2, -1], [2, -4, 1], [1, -3, 1]]


In [97]:
def transpose(a):
    for i in range(len(a)):
        for j in range(len(a[0])):
            if i==j:
                break
            t = a[i][j]
            a[i][j] = a[j][i]
            a[j][i] = t
            
    return a

In [98]:
b = a
b = transpose(b)
print(b)

[[1, -1, 2], [1, 0, 1], [2, 1, 0]]


In [105]:
def inverse(a):
    cof = cofactor(a)
    adj = transpose(cof)
    det = determinant(a)
    inv = []
    for i in range(len(a)):
        col = []
        for j in range(len(a[0])):
            col.append(0)
        inv.append(col)
        
        
    for i in range(len(a)):
        for j in range(len(a[0])):
            inv[i][j] = adj[i][j]/det
    
    return inv

In [106]:
print("The matrix is ", a)
print("transpose of the matrix is ", transpose(a))
print("cofactor matrix of a is ", cofactor(a))
print("Determinant of the matrix is ", determinant(a))
print("Adjoint of the matrix is ", transpose(cofactor(a)))
print("Inverse of the matrix is ", inverse(a))

The matrix is  [[1, 1, 2], [-1, 0, 1], [2, 1, 0]]
transpose of the matrix is  [[1, -1, 2], [1, 0, 1], [2, 1, 0]]
cofactor matrix of a is  [[-1, 2, 1], [2, -4, -3], [-1, 1, 1]]
Determinant of the matrix is  -1
Adjoint of the matrix is  [[-1, 2, -1], [2, -4, 1], [1, -3, 1]]
Inverse of the matrix is  [[1.0, -2.0, 1.0], [-2.0, 4.0, -1.0], [-1.0, 3.0, -1.0]]


In [107]:
#3b using numpy

In [112]:
a = np.array([[1,1,2],[-1,0,1],[2,1,0]])
print("The matrix is ")
print(a)
print("transpose of the matrix is ", np.matrix.transpose(a))
print("cofactor matrix of a is ", np.matrix.transpose(np.matrix.getH(a)))
print("Determinant of the matrix is ", np.linalg.det(a))
print("Adjoint of the matrix is ", np.matrix.getH(a))
print("Inverse of the matrix is ", np.linalg.inv(a))

The matrix is 
[[ 1  1  2]
 [-1  0  1]
 [ 2  1  0]]
transpose of the matrix is  [[ 1 -1  2]
 [ 1  0  1]
 [ 2  1  0]]
cofactor matrix of a is  [[ 1  1  2]
 [-1  0  1]
 [ 2  1  0]]
Determinant of the matrix is  -1.0
Adjoint of the matrix is  [[ 1 -1  2]
 [ 1  0  1]
 [ 2  1  0]]
Inverse of the matrix is  [[ 1. -2. -1.]
 [-2.  4.  3.]
 [ 1. -1. -1.]]
